volumes:
  efs:
    driver: local
    driver_opts:
      type: nfs4
      o: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,noresvport
      device: fs-0627d4a37934a407e.efs.eu-central-1.amazonaws.com:/

services:
  postgres-15:
    user: 33333:33333
    environment:
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/gitpod
    image: postgres
    restart: always
    hostname: postgres
    shm_size: 1g
    ports:
      - "5432:5432"
    volumes:
      - efs:/var/lib/gitpod
